[package]
name = "axum-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { git = "https://github.com/tokio-rs/axum" }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.2.0", features = ["fs", "trace"] }
askama = "0.10"
mime_guess = "2.0.3"
rust-embed="6.3.0"
structopt = "0.3"
tracing = "0.1.29"
tracing-subscriber = { version="0.3.3", features = ["env-filter"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
